cpu-variant = "WDC65C02"
clock-speed-hz = 1843200

[[devices]]
type = "ram"
address = 0x0000
size = "4K"

[[devices]]
type = "rom"
address = 0xE000
size = "8K"
image = "{{ROM_IMAGE}}"
labels = "{{LABELS}}"

[[devices]]
type = "via/6522"
address = 0xFF80

[[devices]]
type = "lfsr"
address = 0xFFF6

[[devices]]
type = "console"
address = 0xFFF8
break = 0x3
